package constants

const PORT = "PORT"

const (
	MONGO_CONNECTION         = "MONGO_CONNECTION"
	MONGO_CONNECTION_TIMEOUT = "MONGO_CONNECTION_TIMEOUT"
	MONGO_DISCONNECT_TIMEOUT = "MONGO_DISCONNECT_TIMEOUT"
	MONGO_DB_NAME            = "MONGO_DB_NAME"
)

const (
	RABBITMQ_CONNECTION   = "RABBITMQ_CONNECTION"
	MESSAGE_CREATED_QUEUE = "MESSAGE_CREATED_QUEUE"
	MESSAGE_DELETED_QUEUE = "MESSAGE_DELETED_QUEUE"
)
