package constants

const TOKEN_HEADER_NAME = "access_token"

const (
	MONGO_CONNECTION         = "MONGO_CONNECTION"
	MONGO_CONNECTION_TIMEOUT = "MONGO_CONNECTION_TIMEOUT"
	MONGO_DISCONNECT_TIMEOUT = "MONGO_DISCONNECT_TIMEOUT"
	MONGO_DB_NAME            = "MONGO_DB_NAME"

	PORT = "PORT"
)
