package constants

const (
	ELASTIC_ADDRESSES = "MONGO_CONNECTION"
	ELASTIC_USERNAME  = "MONGO_CONNECTION_TIMEOUT"
	ELASTIC_PASSWORD  = "MONGO_DISCONNECT_TIMEOUT"

	PORT = "PORT"
)

const (
	RABBITMQ_CONNECTION   = "RABBITMQ_CONNECTION"
	MESSAGE_CREATED_QUEUE = "MESSAGE_CREATED_QUEUE"
	MESSAGE_DELETED_QUEUE = "MESSAGE_DELETED_QUEUE"
)
