package constants

const TOKEN_HEADER_NAME = "access_token"

const (
	MONGO_CONNECTION         = "MONGO_CONNECTION"
	MONGO_CONNECTION_TIMEOUT = "MONGO_CONNECTION_TIMEOUT"
	MONGO_DISCONNECT_TIMEOUT = "MONGO_DISCONNECT_TIMEOUT"

	PORT = "PORT"

	JWT_SECRET_KEY         = "JWT_SECRET_KEY"
	JWT_EXPIRATION_MINUTES = "JWT_EXPIRATION_MINUTES"
)
